### ISSUE TITLE
pandoc-citeproc option?

### ISSUE THREAD

**Issue by kylelundstedt** [rstudio/bookdown-demo#2]
Hi @yihui,

I downloaded the bookdown-demo project, then tried to knit it without making any changes.  As the R Markdown console output below indicates, the Markdown file is created successfully, but the pandoc call fails due to "Filter pandoc-citproc not found".

I'm a newbie when it comes to pandoc and bibliographies, so please forgive me if I have this wrong.  I looked at the bookdown documentation, but couldn't find any related setting that might be specific to the bookdown-demo project.  Is it your intent to require use of pandoc-citeproc at all times?  If so, I think you might want to have a way to ensure users have it installed.

Thanks
Kyle

```
  |.................................................................| 100%
  ordinary text without R code

output file: book.knit.md

/usr/local/bin/pandoc +RTS -K512m -RTS book.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output book.html --smart --email-obfuscation none --standalone --section-divs --table-of-contents --toc-depth 3 --template /Library/Frameworks/R.framework/Versions/3.2/Resources/library/bookdown/templates/gitbook.html --number-sections --css style.css --include-in-header /var/folders/kb/wjssln_13c7c0gwbwvyr9dc00000gn/T//RtmpMU8Dkv/rmarkdown-str50b32b857fd5.html --mathjax --highlight-style pygments --bibliography book.bib --bibliography packages.bib --filter pandoc-citeproc 
pandoc: Filter pandoc-citeproc not found
Error: pandoc document conversion failed with error 85
Execution halted
```

**Comment by yihui** [comment]
So you are on OS X, and it seems you installed Pandoc by yourself. In that case, you also need to install pandoc-citeproc. You didn't say how you installed Pandoc, but my guess is that you installed it from Homebrew? Because if you downloaded Pandoc from its website, you should have already got pandoc-citeproc since it was bundled with pandoc. If you are installed pandoc from Homebrew, just `brew install pandoc-citeproc`, otherwise I cannot think of a possible reason that it could fail, because both RStudio and Pandoc provides pandoc-citeproc, and normally you should not end up with only pandoc but not pandoc-citeproc. To sum up,

- You either do not install Pandoc separately and use the RStudio IDE,
- Or install Pandoc following the links on its website http://pandoc.org/installing.html
- Or `brew install pandoc pandoc-citeproc`

**Comment by kylelundstedt** [comment]
Hi @yihui,
You're correct; I installed pandoc via home-brew.  Installing pandoc-citproc via homebrew fixed the issue.  Thanks!

**Comment by yihui** [comment]
Excellent.
